"""Metadados confirmados por documento, re-derivados da análise manual feita na
conversa de design (ver CHAT_NIVEL_2/*/00_Analise.txt e
01_Arquitetura_e_Criterios.txt).

Granularidade: por documento (às vezes por trecho numerado, nos 8 arquivos de
Sefirot_Conceitos/, mas aqui simplificado para o documento inteiro). As tags
de um documento são aplicadas a TODOS os parágrafos/chunks extraídos dele —
isso é uma simplificação deliberada, documentada, não uma alegação de precisão
por parágrafo.

`chave` é uma substring ASCII segura (sem acentos/aspas curvas/travessões)
usada para localizar o arquivo real dentro da pasta, evitando erro de
correspondência por causa de caracteres especiais nos nomes originais.

Arquivos excluídos por não serem fonte de corpus (cópias de respostas da IA,
ou duplicatas de outro arquivo já presente): Analise_Claude.odt
(Sefirot_Conceitos_2), Uso.txt (Novos/1), kla_114.txt a kla_117.txt (Novos/5,
duplicam Klalei.txt).
"""

DOCUMENTOS = [
    # --- Sefirot_Conceitos ---
    {"pasta": "Sefirot_Conceitos", "chave": "01_Keter", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["Keter", "EinSof"], "sefirot_expressa": [],
     "observacoes": "Keter = intermediary between Ein Sof and Sefirot, root/soul of Sefirot, Ratzon Haelyon. Base da aresta PONTE."},
    {"pasta": "Sefirot_Conceitos", "chave": "02_ChaBaD", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["Chochmah", "Binah", "Daat", "Keter"], "sefirot_expressa": [],
     "observacoes": "Fonte da aresta GOVERNA expandida (7 alvos): Da'at e a essencia de todas as Midot. Abba/Imma/Ben = Chochmah/Binah/Daat."},
    {"pasta": "Sefirot_Conceitos", "chave": "03_ChaGaT", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["Chesed", "Gevurah", "Tiferet"], "sefirot_expressa": ["Chesed", "Gevurah", "Tiferet"],
     "observacoes": "Fonte da aresta SINTETIZA Chesed+Gevurah->Tiferet. EXPRESSA: Abraao/Isaac/Jaco."},
    {"pasta": "Sefirot_Conceitos", "chave": "04_NeHY", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["Netzach", "Hod", "Yesod"], "sefirot_expressa": ["Netzach", "Hod", "Chesed", "Gevurah"],
     "observacoes": "Fonte das arestas SINTETIZA Netzach+Hod->Yesod e CANALIZA. EXPRESSA: parabola pai ensinando o filho."},
    {"pasta": "Sefirot_Conceitos", "chave": "05_Malchut", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["Malchut", "EinSof"], "sefirot_expressa": [],
     "observacoes": "Malchut = vaso receptor final, origem da luz revelada do EinSof, identica a Shechinah."},
    {"pasta": "Sefirot_Conceitos", "chave": "Sefirot_Grafo_1", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["EinSof", "Malchut"], "sefirot_expressa": [],
     "observacoes": "Etimologia Adon Olam, guematria Adon=Ein/Olam=Sof, Tzimtzum como autolimitacao."},
    {"pasta": "Sefirot_Conceitos", "chave": "Sefirot_Grafo_2", "autoria": "fonte_externa",
     "temas": ["Fundamentos"],
     "sefirot_define": ["EinSof", "AdamKadmon", "Keter", "Chochmah", "Binah", "Daat", "Chesed",
                         "Gevurah", "Tiferet", "Netzach", "Hod", "Yesod", "Malchut"],
     "sefirot_expressa": [],
     "observacoes": "Tabela resumo, DEFINE thin, superada pelos docs posteriores. Relacao Adon Olam x EinSof."},
    {"pasta": "Sefirot_Conceitos", "chave": "Sefirot_Grafo_3", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["EinSof", "AdamKadmon", "Keter"],
     "sefirot_expressa": ["Chochmah", "Binah", "Daat", "Chesed", "Gevurah", "Tiferet", "Netzach", "Hod", "Yesod", "Malchut"],
     "observacoes": "AdamKadmon detalhado. Kochot HaNefesh: 1a EXPRESSA real do corpus."},

    # --- Sefirot_Conceitos_2 ---
    {"pasta": "Sefirot_Conceitos_2", "chave": "01.odt", "autoria": "fonte_externa",
     "temas": ["Fundamentos"],
     "sefirot_define": ["Keter", "Chochmah", "Binah", "Daat", "Chesed", "Gevurah", "Tiferet", "Netzach", "Hod", "Yesod", "Malchut"],
     "sefirot_expressa": ["Keter", "Chochmah", "Binah", "Daat", "Malchut"],
     "observacoes": "Chabad.org 'The Sefirot' (Dubov), 'Ten Powers of the Soul' (Miller), Tanya cap.3. Preenche EXPRESSA para Keter/Chochmah/Binah/Daat/Malchut."},
    {"pasta": "Sefirot_Conceitos_2", "chave": "02.odt", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["Keter", "Chochmah", "Binah", "Daat", "Malchut"],
     "sefirot_expressa": ["Keter", "Chochmah", "Binah", "Daat", "Malchut"],
     "observacoes": "Exemplo do medico fumante (Daat) com fonte. Guia do Omer (Jacobson) para Malchut."},
    {"pasta": "Sefirot_Conceitos_2", "chave": "03.odt", "autoria": "fonte_externa",
     "temas": ["Fundamentos"],
     "sefirot_define": ["Keter", "Chochmah", "Binah", "Daat", "Chesed", "Gevurah", "Tiferet", "Netzach", "Hod", "Yesod", "Malchut"],
     "sefirot_expressa": ["Chesed", "Gevurah", "Tiferet", "Netzach", "Hod", "Yesod", "Malchut"],
     "observacoes": "Correspondencia biblica completa das 7 Sefirot inferiores, ligada a Contagem do Omer (Jacobson). Igrot Kodesh vol.4."},
    {"pasta": "Sefirot_Conceitos_2", "chave": "04.odt", "autoria": "fonte_externa",
     "temas": ["Fundamentos"],
     "sefirot_define": ["Keter", "Chochmah", "Binah", "Daat", "Chesed", "Gevurah", "Tiferet", "Netzach", "Hod", "Yesod", "Malchut"],
     "sefirot_expressa": ["Keter", "Chochmah", "Binah", "Daat", "Chesed", "Gevurah", "Tiferet", "Netzach", "Hod", "Yesod", "Malchut"],
     "observacoes": "Nomeia 'Moach Shalit Al HaLev' (Tanya caps.3 e 16) explicitamente. Ma'aseh Hu HaIkar (Tanya 35/37) para Malchut."},
    {"pasta": "Sefirot_Conceitos_2", "chave": "05.odt", "autoria": "fonte_externa",
     "temas": ["Fundamentos"],
     "sefirot_define": ["Keter", "Chochmah", "Binah", "Daat", "Chesed", "Gevurah", "Tiferet", "Netzach", "Hod", "Yesod", "Malchut"],
     "sefirot_expressa": ["Chochmah", "Binah", "Daat", "Chesed", "Gevurah", "Tiferet", "Netzach", "Hod", "Yesod", "Malchut"],
     "observacoes": "Citacoes diretas com URL chabad.org por trecho. Medico fumante repetido com fonte especifica."},

    # --- Novos/1 ---
    {"pasta": "Novos/1", "chave": "13 Meditations", "autoria": "fonte_externa",
     "temas": ["Financas"], "sefirot_define": [], "sefirot_expressa": ["Malchut", "Chesed"],
     "observacoes": "Tzvi Freeman, chabad.org. Likkutei Sichot, Igeret Hakodesh 11, Torat Menachem 5742."},
    {"pasta": "Novos/1", "chave": "Anxiety", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Nefesh_nivel", "Ruach_nivel", "Neshamah_nivel", "Chayah_nivel", "Yechidah_nivel"],
     "observacoes": "Ginsburgh, inner.org/mental/mental40.htm. 1a fonte dos 5 niveis da alma (via Jo)."},

    # --- Novos/2 ---
    {"pasta": "Novos/2", "chave": "Boosting Self-Esteem", "autoria": "fonte_externa",
     "temas": ["Autoestima"], "sefirot_define": [], "sefirot_expressa": ["Keter"],
     "observacoes": "chabad.org Q&A. Valor intrinseco da alma."},
    {"pasta": "Novos/2", "chave": "Educacacao", "autoria": "autor_projeto",
     "temas": ["Educacao", "Fundamentos"], "sefirot_define": ["AdamKadmon", "Chochmah", "Binah"],
     "sefirot_expressa": ["Chochmah", "Binah"],
     "observacoes": "TEXTO PROPRIO DO USUARIO ('Sistema Talmud'). Cita o Zohar: intelecto domina o coracao (3a fonte de Moach Sholet Al HaLev). Chochmah/Binah = 'dois amigos inseparaveis' (Zohar), principio holistico (cada Sefirah contem todas as demais)."},
    {"pasta": "Novos/2", "chave": "Moral Obligation", "autoria": "fonte_externa",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": ["Chochmah", "Binah", "Daat"],
     "observacoes": "Provavel carta/proclamacao publica do Rebbe."},

    # --- Novos/3 ---
    {"pasta": "Novos/3", "chave": "For Whom", "autoria": "fonte_externa",
     "temas": ["Proposito", "Fundamentos"], "sefirot_define": [], "sefirot_expressa": ["Netzach", "Malchut"],
     "observacoes": "inner.org. Talmud. Moises=Netzach, David=Malchut reforcados."},

    # --- Novos/4 ---
    {"pasta": "Novos/4", "chave": "Approach_39", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Nefesh_nivel", "Ruach_nivel", "Neshamah_nivel", "Chayah_nivel", "Yechidah_nivel"],
     "observacoes": "inner.org/mental/mental39.htm. 2a fonte dos 5 niveis da alma."},

    # --- Novos/5 ---

    # --- Novos/6 ---
    {"pasta": "Novos/6", "chave": "Rectified Ego", "autoria": "fonte_externa",
     "temas": ["Lideranca", "Humildade"], "sefirot_define": [], "sefirot_expressa": ["Malchut", "Hod"],
     "observacoes": "inner.org/leader/leader3.htm. Guematria ani/ayin. David vs. Adoniyahu."},
    {"pasta": "Novos/6", "chave": "Messianic Spark", "autoria": "fonte_externa",
     "temas": ["Lideranca", "Proposito", "Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Nefesh_nivel", "Ruach_nivel", "Neshamah_nivel", "Chayah_nivel", "Yechidah_nivel"],
     "observacoes": "inner.org/leader/leader1.htm. 3a fonte independente dos 5 niveis da alma, a mais citavel."},

    # --- Novos/7 ---
    {"pasta": "Novos/7", "chave": "Self-Esteem.odt", "autoria": "fonte_externa",
     "temas": ["Autoestima"], "sefirot_define": [], "sefirot_expressa": ["Yesod", "Malchut", "Keter"],
     "observacoes": "chabad.org Q&A. Rabbi Moshe Cordevero."},
    {"pasta": "Novos/7", "chave": "autoestima.odt", "autoria": "fonte_externa",
     "temas": ["Autoestima"], "sefirot_define": [], "sefirot_expressa": ["Keter", "Hod", "Malchut"],
     "observacoes": "Sintese/indice, nao fonte primaria."},
    {"pasta": "Novos/7", "chave": "Humility & Happiness", "autoria": "fonte_externa",
     "temas": ["Autoestima", "Saude_Mental"], "sefirot_define": ["Hod"], "sefirot_expressa": ["Hod"],
     "observacoes": "Discurso real do Rabino Shalom Dovber (Rashab), 1918. chabad.org."},
    {"pasta": "Novos/7", "chave": "Ego, And", "autoria": "fonte_externa",
     "temas": ["Autoestima"], "sefirot_define": [], "sefirot_expressa": ["Keter", "Hod"],
     "observacoes": "chabad.org Q&A. Talentos como dom Divino a desenvolver."},
    {"pasta": "Novos/7", "chave": "Self-Esteem And", "autoria": "fonte_externa",
     "temas": ["Autoestima"], "sefirot_define": [], "sefirot_expressa": ["Yesod", "Malchut", "Keter"],
     "observacoes": "DUPLICATA de Self-Esteem.odt (mesmo artigo chabad.org)."},
    {"pasta": "Novos/7", "chave": "Humble Self-Esteem", "autoria": "fonte_externa",
     "temas": ["Autoestima", "Humildade"], "sefirot_define": ["Hod"], "sefirot_expressa": ["Hod", "Keter"],
     "observacoes": "Sichah real do Rebbe (Behar-Bechukosai), chabad.org/therebbe."},

    # --- Novos/8 ---
    {"pasta": "Novos/8", "chave": "speak-to-the-heart", "autoria": "fonte_externa",
     "temas": ["Lideranca"], "sefirot_define": ["Netzach", "Hod", "Yesod"], "sefirot_expressa": ["Netzach", "Hod", "Yesod"],
     "observacoes": "inner.org. NAO e sobre Casamento apesar da pasta. Or HaChaim."},
    {"pasta": "Novos/8", "chave": "Cultivating Selflessness", "autoria": "fonte_externa",
     "temas": ["Casamento"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Olam_dimensao", "Shanah_dimensao", "Nefesh_dimensao"],
     "observacoes": "inner.org/covenant/marr09.htm. Trio Olam-Shanah-Nefesh."},
    {"pasta": "Novos/8", "chave": "Finding Eve", "autoria": "fonte_externa",
     "temas": ["Casamento"], "sefirot_define": [], "sefirot_expressa": [],
     "observacoes": "inner.org/covenant/marr02.htm. Talmud Kidushin 2b, Bereishit Rabbah 17:6."},
    {"pasta": "Novos/8", "chave": "Have You Found", "autoria": "fonte_externa",
     "temas": ["Casamento"], "sefirot_define": [], "sefirot_expressa": ["Chesed"],
     "observacoes": "inner.org/covenant/marr01.htm. Talmud Yevamot 63b, Zohar 343b."},
    {"pasta": "Novos/8", "chave": "Three Levels", "autoria": "fonte_externa",
     "temas": ["Casamento"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Tzadik", "Beinoni"],
     "observacoes": "inner.org/covenant/marr11.htm. Eixo Tzadik-Beinoni (Tanya)."},
    {"pasta": "Novos/8", "chave": "True State", "autoria": "fonte_externa",
     "temas": ["Saude_Mental", "Autoestima"], "sefirot_define": [], "sefirot_expressa": ["Keter"],
     "observacoes": "Carta datada do Rebbe (5719). NAO e sobre Casamento apesar da pasta."},

    # --- Novos/9 ---
    {"pasta": "Novos/9", "chave": "Four Reasons", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["EinSof", "Chochmah", "Malchut"], "sefirot_expressa": [],
     "observacoes": "inner.org. FONTE-ANCORA de Dira BeTachtonim como razao PRIMARIA em Chabad (Tanya)."},
    {"pasta": "Novos/9", "chave": "Purpose of this World", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["EinSof"], "sefirot_expressa": [],
     "observacoes": "chabad.org, provavel Tzvi Freeman. Registro popular do mesmo tema do Partzuf."},
    {"pasta": "Novos/9", "chave": "Nine Principles", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["EinSof", "Chochmah", "Binah"], "sefirot_expressa": [],
     "observacoes": "inner.org, serie 'Wonders' (Ginsburgh), Parte 2. Nachmanides, Maharal. Chochmah/Binah = 'dois amigos que nunca se separam' (confirma Educacacao.odt)."},
    {"pasta": "Novos/9", "chave": "Essence Dwells", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": [], "sefirot_expressa": [],
     "observacoes": "DUPLICATA/variante de 'A Dwelling Below' (Novos/1). Nao conta como fonte independente."},

    # --- Novos/10 ---
    {"pasta": "Novos/10", "chave": "Kesef", "autoria": "fonte_externa",
     "temas": ["Financas"], "sefirot_define": [], "sefirot_expressa": ["Malchut", "Chesed"],
     "observacoes": "chabad.org. Mitzvot de honestidade e redistribuicao. Talmud: primeira pergunta do tribunal celestial."},

    # --- Divididos/ (documentos com dispersão temática alta, divididos em 2026-07-28 — ver 00_Estado_Atual.txt seção 4.16) ---
    # de "A Dwelling Below.odt"
    {"pasta": "Divididos/a_dwelling_below", "chave": "01_o_decreto_rescindido_fundamento_da_morada_abaixo.txt", "autoria": "fonte_externa",
     "temas": ["Fundamentos", "Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho apresenta a parábola do decreto rescindido para introduzir o conceito central de 'dwelling below' como o propósito da Criação e da entrega da Torá."},
    {"pasta": "Divididos/a_dwelling_below", "chave": "02_onde_a_essência_habita_o_diálogo_entre_os_anjos_e_o_criador.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": ["EinSof"], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Um diálogo alegórico entre os anjos e o Criador em Sinai explica, através da Luz Infinita e sua contração, por que D'us escolheu o mundo mais baixo e material como Sua morada essencial."},
    {"pasta": "Divididos/a_dwelling_below", "chave": "03_proximidade_divina_ação_no_mundo_e_união_céu-terra.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho contrasta reclusão contemplativa e engajamento ativo no mundo para argumentar que a proximidade a Deus vem de habitar e cuidar do mundo material, unindo Céu e Terra em uma só forma."},
    {"pasta": "Divididos/a_dwelling_below", "chave": "04_na_essência_além_da_sabedoria_e_do_conhecimento.txt", "autoria": "fonte_externa",
     "temas": ["Proposito", "Fundamentos"], "sefirot_define": ["EinSof"], "sefirot_expressa": ["Chochmah", "Daat"],
     "entidades": [],
     "observacoes": "O trecho aponta para uma Essência Divina além até da sabedoria e do conhecimento, onde nada resta exceto o propósito ardente do momento presente."},
    {"pasta": "Divididos/a_dwelling_below", "chave": "05_a_obra_das_nossas_mãos_dus_na_terra_não_apenas_no_céu.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho argumenta que o propósito da criação é fazer da terra, e não do céu, a morada da presença essencial de D'us, através da obra das mãos humanas."},
    {"pasta": "Divididos/a_dwelling_below", "chave": "06_um_só_mundo_a_recusa_da_dicotomia_sagrado-secular.txt", "autoria": "fonte_externa",
     "temas": ["Financas"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho rejeita a dicotomia entre vida profissional/secular e espiritualidade, afirmando que existe apenas um mundo real governado por um único D'us."},
    # de "Basis of Humility.odt"
    {"pasta": "Divididos/basis_of_humility", "chave": "01_fundamento_da_humildade_autovalorização_rei_david_e_o_vazio.txt", "autoria": "fonte_externa",
     "temas": ["Humildade", "Autoestima"], "sefirot_define": [], "sefirot_expressa": ["EinSof"],
     "entidades": [],
     "observacoes": "O trecho fundamenta a humildade na consciência do próprio valor da alma divina contrastada com a falha em manifestá-lo, ilustrada pelo exemplo do Rei David e pela ideia de que todo 'espaço' vazio de consciência Divina se torna vulnerável ao vazio existencial."},
    {"pasta": "Divididos/basis_of_humility", "chave": "02_a_humildade_como_fonte_de_alegria_o_exemplo_do_patriarca_jac.txt", "autoria": "fonte_externa",
     "temas": ["Humildade", "Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho explora como a verdadeira humildade — exemplificada por Jacó — liberta a pessoa de expectativas e ressentimentos, tornando-se a base psicológica para a felicidade constante."},
    {"pasta": "Divididos/basis_of_humility", "chave": "03_humildade_verdadeira_vs_autodepreciação_patológica.txt", "autoria": "fonte_externa",
     "temas": ["Humildade", "Autoestima", "Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho distingue a humildade saudável, enraizada na conexão com a alma Divina, da autodepreciação patológica causada pela desconexão espiritual e foco excessivo na natureza animal, propondo a espiritualização como cura."},
    {"pasta": "Divididos/basis_of_humility", "chave": "04_aplicações_práticas_da_humildade_educação_dos_filhos_e_vida.txt", "autoria": "fonte_externa",
     "temas": ["Humildade", "Casamento", "Educacao", "Autoestima"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho aplica o valor da humildade a contextos práticos concretos — educação dos filhos e resolução de conflitos conjugais — propondo que cada cônjuge se veja como causa principal do problema e reconheça que tudo, incluindo esposa e filhos, é um dom imerecido de D'us."},
    # de "Combating Sadness.odt"
    {"pasta": "Divididos/combating_sadness", "chave": "01_superando_a_tristeza_através_da_providência_divina_e_do_prop.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental", "Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho ensina a superar a tristeza através da fé na providência divina individual e do redirecionamento intelectual do pensamento para o propósito de vida e a missão no mundo."},
    {"pasta": "Divididos/combating_sadness", "chave": "02_combatendo_a_depressão_por_fracasso_nos_estudos_o_yetzer_har.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental", "Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Carta de orientação sobre como combater sentimentos de fracasso e depressão nos estudos através da determinação racional que sobrepõe a emoção, identificando a tristeza como arma do Yetzer Hara."},
    {"pasta": "Divididos/combating_sadness", "chave": "03_a_visão_tradicional_sobre_melancolia_e_a_insatisfação_como_s.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho aborda a visão tradicional contra a melancolia e explica como a insatisfação consigo mesmo é sinal saudável de vitalidade, distinguindo-a do desânimo destrutivo instigado pelo yetzer hara."},
    {"pasta": "Divididos/combating_sadness", "chave": "04_amargura_e_melancolia_como_obra_do_outro_lado_o_remédio_do_c.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental", "Lideranca"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Beinoni"],
     "observacoes": "Carta do Rebe a um rabino desanimado, atribuindo amargura e melancolia ao 'Outro Lado' e prescrevendo estudo de Chassidut, confiança (bitachon) e farbrengens alegres como remédio, mantendo-se firme em seu posto de liderança."},
    {"pasta": "Divididos/combating_sadness", "chave": "05_o_poder_do_pensamento_positivo_contra_o_desânimo_e_o_coração.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho reúne cartas do Rebbe sobre como combater desânimo, tristeza e coração partido através do pensamento positivo e disciplina racional, alertando para seus efeitos nocivos à saúde e à percepção da realidade."},
    {"pasta": "Divididos/combating_sadness", "chave": "06_transformando_o_vazio_e_a_rejeição_em_impulso_para_o_serviço.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental", "Autoestima"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho ensina, através da metáfora do vácuo na seringa e de uma carta do Rebe, a transformar sentimentos de vazio, inutilidade e desespero em motivação intensificada para o serviço Divino, enfatizando que servir a D'us com alegria é uma lei fundamental (não apenas uma virtude opcional), sustentada pelo ensinamento da Tanya sobre a alegria intrínseca da alma."},
    {"pasta": "Divididos/combating_sadness", "chave": "07_fortalecido_pelas_bênçãos_do_rebbe_a_alegria_que_atrai_bonda.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": ["Chesed", "Gevurah"],
     "entidades": ["Tzadik"],
     "observacoes": "O Rebbe encoraja a superar tristeza e depressão através da fé nas bênçãos do tzadik e da alegria, citando o Zohar sobre como o estado emocional do mundo inferior determina se recebe bondade ou severidade do Alto."},
    {"pasta": "Divididos/combating_sadness", "chave": "08_o_desânimo_como_artimanha_do_yetzer_hara_e_a_consciência_de.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental", "Autoestima"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho ensina que o desânimo e a percepção excessiva de falhas são artimanhas do yetzer hara que devem ser combatidas com discernimento e substituídas pela alegria no serviço Divino, conforme o Tanya."},
    {"pasta": "Divididos/combating_sadness", "chave": "09_combatendo_a_melancolia_através_do_amor_ao_próximo_torá_oraç.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": ["Chesed"],
     "entidades": [],
     "observacoes": "O trecho orienta como superar tristeza e desesperança através de meditação sobre amor ao próximo, estudo intensivo de Torá, oração e atos de bondade, enfatizando o poder da luz espiritual sobre a escuridão emocional."},
    {"pasta": "Divididos/combating_sadness", "chave": "10_superando_a_angústia_espiritual_introdução_à_carta_e_o_dom_d.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Carta de aconselhamento espiritual que trata o desespero e a angústia como armadilha emocional do 'yetzer hara', propondo a análise racional como antídoto, no contexto de um artista que busca orientação pessoal."},
    {"pasta": "Divididos/combating_sadness", "chave": "11_a_metáfora_do_artista_aplicada_à_revelação_da_essência_divin.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": ["Chochmah"],
     "entidades": [],
     "observacoes": "O trecho usa a metáfora do artista que revela a essência oculta de uma imagem para explicar como a alma judaica, derivada da Sabedoria Divina, deve manifestar sua verdadeira essência através do serviço, do esforço e dos processos de refinamento (birurim), superando o ocultamento das camadas externas da criação."},
    {"pasta": "Divididos/combating_sadness", "chave": "12_não_há_lugar_para_o_desespero_confiar_na_garantia_divina_aci.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental", "Autoestima"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho ensina que o sentimento de desespero e a autopercepção negativa devem ceder à garantia racional e divina de que ninguém está irremediavelmente banido, valorizando o esforço mínimo como suficiente."},
    {"pasta": "Divididos/combating_sadness", "chave": "13_canalizando_a_melancolia_para_o_estudo_da_torá_e_banindo_pen.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Cartas de orientação sobre como transformar a melancolia e o desespero em combustível para o estudo da Torá, banindo pensamentos negativos através da disciplina mental e do foco em Deus."},
    {"pasta": "Divididos/combating_sadness", "chave": "14_a_desesperança_contradiz_a_fé_na_providência_divina_inclusiv.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental", "Casamento"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O Rebe orienta contra a desesperança, afirmando que ela contradiz a fé judaica na Providência Divina individual, aplicando esse princípio especificamente ao sofrimento de um casal que espera por filhos."},
    {"pasta": "Divididos/combating_sadness", "chave": "15_banindo_pensamentos_suicidas_através_da_providência_divina_e.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental", "Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Nefesh_dimensao"],
     "observacoes": "O trecho usa a contemplação da providência divina individual e da missão insubstituível da alma no mundo como antídoto racional contra pensamentos suicidas."},
    {"pasta": "Divididos/combating_sadness", "chave": "16_o_propósito_da_vida_e_o_dever_de_retribuir_uma_repreensão_ao.txt", "autoria": "fonte_externa",
     "temas": ["Proposito", "Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Repreensão a uma pessoa autocentrada, ensinando que o universo opera num sistema de dar e receber e que cada indivíduo — especialmente o judeu no pós-Holocausto — tem o dever de retribuir à sociedade e ao seu povo os dons recebidos."},
    {"pasta": "Divididos/combating_sadness", "chave": "17_a_torá_como_preservadora_eterna_do_povo_judeu_e_o_chamado_à.txt", "autoria": "fonte_externa",
     "temas": ["Proposito", "Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho une uma reflexão sobre a Torá e Mitzvot como o 'fio de ouro' eterno que preservou o povo judeu através da história com um conselho pessoal a um jovem judeu para superar o egocentrismo emocional através da ação altruísta e da Teshuvá (retorno à essência da alma) nos dias de Elul."},
    {"pasta": "Divididos/combating_sadness", "chave": "18_utilizando_a_marah_shechorá_para_o_estudo_da_torá_e_fortalec.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho aconselha usar a melancolia (marah shechorah) para intensificar o estudo da Torá e fortalecer o bitachon como remédio para a angústia e problemas de saúde mental."},
    {"pasta": "Divididos/combating_sadness", "chave": "19_o_impacto_do_desânimo_na_família_e_a_superação_do_medo_pela.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental", "Casamento"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho aconselha superar desânimo e medo através de bitachon e da alegria no serviço divino, ressaltando o impacto do estado emocional do indivíduo sobre sua família."},
    {"pasta": "Divididos/combating_sadness", "chave": "20_servir_a_dus_com_alegria_como_arma_espiritual_contra_o_desân.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho ensina que servir a D'us com alegria é um comando e uma ferramenta espiritual ativa para vencer o desânimo e a tristeza, comparando o serviço divino a um soldado que canta antes da batalha, com apoio nas fontes do Baal Shem Tov, Rambam e no Tanya."},
    {"pasta": "Divididos/combating_sadness", "chave": "21_encontrando_alegria_através_da_benevolência_e_reconhecendo_o.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": ["Chesed"],
     "entidades": [],
     "observacoes": "O trecho aconselha superar tristeza e depressão através de atos de benevolência e da contemplação racional da presença e alegria constantes de D'us, valorizando o bem feito acima do status pessoal."},
    {"pasta": "Divididos/combating_sadness", "chave": "22_superando_a_negatividade_quando_a_teoria_não_basta_frente_à.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Carta de orientação pessoal sobre como reconhecer e superar táticas do yetzer hara que geram depressão e desânimo, enfatizando o uso da razão e reservas internas para restaurar o ânimo e a saúde mental."},
    {"pasta": "Divididos/combating_sadness", "chave": "23_transformando_sentimentos_de_desânimo_passo_a_passo.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Carta do Rebbe orientando uma pessoa deprimida a reverter seu estado de ânimo através de pequenos passos concretos guiados pela razão, não pela emoção."},
    {"pasta": "Divididos/combating_sadness", "chave": "24_confiança_na_providência_divina_frente_a_decepções_pessoais.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho reúne cartas do Rebbe orientando indivíduos a superar tristeza, decepção e moroseness através da confiança (bitachon) na Providência Divina, da alegria no serviço a D'us e do estudo de textos apropriados como o Tanya."},
    {"pasta": "Divididos/combating_sadness", "chave": "25_discernindo_a_origem_do_remorso_e_o_poder_do_pensamento_posi.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho ensina a discernir se pensamentos de remorso vêm do bom ou do mau impulso pelos seus frutos, e prescreve o uso deliberado do pensamento positivo — inclusive redirecionando a mente para a Torá — como forma de moldar a realidade e superar melancolia e desânimo."},
    {"pasta": "Divididos/combating_sadness", "chave": "26_pensamentos_negativos_prejudicam_a_saúde_confiança_no_dus_qu.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Carta de orientação sobre como superar pensamentos negativos e ansiedade quanto à saúde através da confiança (bitachon) em D'us como Curador, mantendo o serviço com alegria e propósito."},
    {"pasta": "Divididos/combating_sadness", "chave": "27_buscando_a_verdadeira_causa_da_tristeza_e_corrigindo-a_com_a.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Carta de orientação sobre como identificar a causa real da tristeza e superá-la através da gratidão, fé e observância plena da vida judaica (tefilin, mezuzot, tzedaká)."},
    {"pasta": "Divididos/combating_sadness", "chave": "28_desespero_infundado_e_fantasias_catastróficas_contradizidas.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O Rebe responde a fantasias de desespero e ideias de separação divina, afirmando que nada pode separar o judeu de D'us e que a confiança na providência constante deve substituir a melancolia."},
    {"pasta": "Divididos/combating_sadness", "chave": "29_as_descidas_da_vida_não_são_motivo_para_desânimo.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho ensina que as 'descidas' materiais da vida não devem gerar desânimo, mas sim despertar fé e confiança internas que se manifestam como espírito corajoso e estabilidade emocional."},
    # de "Education and Leadership.odt"
    {"pasta": "Divididos/education_and_leadership", "chave": "01_introdução_educação_liderança_e_a_parábola_do_trem.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca", "Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho introduz o tema educação-liderança através da parábola chassídica do trem, contrastando o modelo tradicional (rebe como único motor) com a visão Chabad de que cada pessoa deve se tornar um 'motor', ou seja, educador e líder."},
    {"pasta": "Divididos/education_and_leadership", "chave": "02_o_nome_divino_e_a_letra_yud_o_ponto_essencial_mission_statem.txt", "autoria": "fonte_externa",
     "temas": ["Educacao"], "sefirot_define": ["Chochmah"], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho introduz o Nome Divino de quatro letras como estrutura educativa em quatro estágios, focando na letra Yud como o 'ponto' essencial que condensa a mission statement do Rebbe (amor a D-us, à Torá e ao próximo)."},
    {"pasta": "Divididos/education_and_leadership", "chave": "03_a_letra_heh_currículo_de_estudo_diário.txt", "autoria": "fonte_externa",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho detalha o currículo diário/semanal/anual de estudo de Torá (Rashi, Tanya, Salmos, Rambam, Talmud, Halachá) associado à letra Heh do Nome Divino, simbolizando a expansão do 'ponto' original em um corpo abrangente de conhecimento judaico para vivência plena da Torá."},
    {"pasta": "Divididos/education_and_leadership", "chave": "04_a_letra_heh_os_dez_mivtzoim_e_as_leis_noaítas.txt", "autoria": "fonte_externa",
     "temas": ["Educacao", "Lideranca"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Mashiach"],
     "observacoes": "O trecho descreve os Dez Mivtzoim do Rebbe como expansão prática do amor a D'us, à Torá e ao próximo, e destaca a difusão das Sete Leis de Noach como código moral universal, culminando na expectativa do Moshiach."},
    {"pasta": "Divididos/education_and_leadership", "chave": "05_a_letra_vav_educação_formal_e_tradicional.txt", "autoria": "fonte_externa",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": ["Daat"],
     "entidades": [],
     "observacoes": "O trecho descreve o sistema educacional formal e informal do Lubavitch, com a Vav do Nome Divino simbolizando a comunicação e transmissão das ensinanças aos indivíduos e à sociedade, destacando a filosofia educacional inclusiva e transformadora do Rebe."},
    {"pasta": "Divididos/education_and_leadership", "chave": "06_a_letra_vav_expansão_além_da_comunidade_chabad_houses_e_camp.txt", "autoria": "fonte_externa",
     "temas": ["Educacao", "Lideranca"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Trecho histórico-institucional sobre a expansão da liderança educacional do Rebbe além da comunidade tradicional, através de Chabad Houses, Campus Outreach, Aleph Institute e a campanha do Moment of Silence, culminando no Education Day USA."},
    {"pasta": "Divididos/education_and_leadership", "chave": "07_a_letra_vav_cartas_a_líderes_mundiais_e_novas_mídias.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca", "Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho documenta o engajamento do Rebbe com líderes mundiais (Reagan, Thatcher) pela promoção das Leis Noaicas e educação moral, além da expansão do outreach chassídico para novas mídias digitais."},
    {"pasta": "Divididos/education_and_leadership", "chave": "08_a_letra_heh_final_a_imagem_do_sol_e_da_lua_na_liderança.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca", "Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho usa a imagem do sol e da lua do Rebbe para ilustrar como o aluno se torna educador e líder, mostrando a interdependência dinâmica entre inspirar e ser inspirado na transmissão de Torá e valores."},
    {"pasta": "Divididos/education_and_leadership", "chave": "09_a_letra_heh_final_a_canção_do_mar_e_o_modelo_dos_shluchim.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca"], "sefirot_define": [], "sefirot_expressa": ["Chochmah", "Malchut"],
     "entidades": [],
     "observacoes": "O trecho usa a estrutura das letras do Nome Divino (Yud-Heh-Vav-Heh) para explicar como Moshe capacitou os israelitas a cantar com inspiração própria, servindo de modelo para a liderança carismática mas fiel dos Shluchim e Shluchot do Rebbe."},
    {"pasta": "Divididos/education_and_leadership", "chave": "10_lamplighters_a_liderança_do_rebe_hoje_e_o_exemplo_da_ucrânia.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho descreve o modelo de liderança do Rebe através da rede de shluchim e da metáfora do 'lamplighter', ilustrado pelo exemplo concreto de um Shaliach que retorna à Ucrânia durante a guerra para guiar sua comunidade."},
    {"pasta": "Divididos/education_and_leadership", "chave": "11_todos_devemos_ser_líderes_a_história_do_vodka_e_conclusão.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca", "Educacao"], "sefirot_define": [], "sefirot_expressa": ["Malchut"],
     "entidades": [],
     "observacoes": "Através da história do Rebbe distribuindo vodka como 'shelichus', o trecho ensina que todo ser humano é um emissário/líder, cuja missão coletiva completa a letra Heh do Nome Divino e transforma o mundo em morada para o Divino."},
    # de "Five Dynamics of Leadership.odt"
    {"pasta": "Divididos/five_dynamics_of_leadership", "chave": "01_liderança_pelo_consenso_o_exemplo_de_moisés_e_josué.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho discute a liderança genuína baseada em consenso, empatia e vínculo pessoal, ilustrada pela transição de Moisés para Josué, contrastando autoridade imposta com liderança relacional."},
    {"pasta": "Divididos/five_dynamics_of_leadership", "chave": "02_paradoxo_tzimtzum_e_a_integração_de_opostos_na_torá.txt", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["EinSof"], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho explora, via o paradoxo do tzimtzum kabbalístico, como a Torá integra opostos e contradições — exemplificado pelas duas árvores do Éden, pelo Shabat e pelas exceções à regra no caminho do ba'al teshuvah."},
    {"pasta": "Divididos/five_dynamics_of_leadership", "chave": "03_ego_rectificado_humildade_e_a_busca_da_justiça_equilibrada.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca", "Humildade"], "sefirot_define": ["Malchut"], "sefirot_expressa": [],
     "entidades": ["Mashiach"],
     "observacoes": "O trecho discute a liderança judaica como expressão de Malchut, exigindo um ego rectificado e humilde (como Moisés), e explora como a busca pela justiça deve equilibrar verdade e paz, culminando na figura do Mashiach como síntese ideal."},
    {"pasta": "Divididos/five_dynamics_of_leadership", "chave": "04_síntese_messiânica_verdade_e_paz_unidas_pela_liderança_ilumi.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Mashiach"],
     "observacoes": "O trecho explora a centelha messiânica presente em cada judeu e o versículo dos Salmos como metáfora para unir verdade e paz através de uma liderança iluminada."},
    # de "Four Crowns and the Hierarchy of Needs.odt"
    {"pasta": "Divididos/four_crowns_and_the_hierarchy_of_needs", "chave": "01_as_três_coroas_do_tabernáculo_e_a_análise_numérica.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho analisa as três coroas doiradas dos vasos do Tabernáculo (arca, mesa, altar) correspondentes às coroas da Torá, do sacerdócio e da realeza, acrescentando a quarta coroa do 'bom nome', e sustenta essa leitura por meio de uma análise gemátrica dos versículos de Terumá."},
    {"pasta": "Divididos/four_crowns_and_the_hierarchy_of_needs", "chave": "02_a_coroa_como_keter_a_luz_que_circunda_todos_os_mundos.txt", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["Keter"], "sefirot_expressa": [],
     "entidades": ["Makif"],
     "observacoes": "O trecho define Keter como a sefirah da coroa, a luz infinita e circundante (makif) que transcende o intelecto e envolve todos os mundos, associando-a ao nome do Baal Shem Tov."},
    {"pasta": "Divididos/four_crowns_and_the_hierarchy_of_needs", "chave": "03_as_três_coroas_como_áreas_da_vida_corpo_relações_e_alma.txt", "autoria": "fonte_externa",
     "temas": ["Proposito", "Autoestima"], "sefirot_define": [], "sefirot_expressa": ["Malchut", "Keter"],
     "entidades": [],
     "observacoes": "O trecho usa as três coroas do Tabernáculo (mesa do pão, altar do incenso e arca) como metáfora para três áreas da vida — física, relacional e espiritual — em paralelo à hierarquia de necessidades de Maslow."},
    {"pasta": "Divididos/four_crowns_and_the_hierarchy_of_needs", "chave": "04_correspondência_com_a_pirâmide_de_maslow.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho compara os três vasos do Tabernáculo (mesa, altar dourado, arca) com os níveis físico, relacional e de autorrealização da pirâmide de Maslow, destacando que cada nível possui condições espirituais/psicológicas que o sustentam."},
    {"pasta": "Divididos/four_crowns_and_the_hierarchy_of_needs", "chave": "05_as_coroas_faltantes_segurança_autoestima_e_a_coroa_da_alma.txt", "autoria": "fonte_externa",
     "temas": ["Autoestima"], "sefirot_define": [], "sefirot_expressa": ["Keter"],
     "entidades": [],
     "observacoes": "O trecho correlaciona a hierarquia de Maslow com o conceito de 'coroa' (Keter), identificando duas coroas ausentes no modelo original — a da autoestima nas relações e a da alma/autorrealização — além da 'coroa do bom nome', que a Chassidut ajudará a definir."},
    {"pasta": "Divididos/four_crowns_and_the_hierarchy_of_needs", "chave": "06_síntese_final_tabela_de_correspondências_prazer_e_fé.txt", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": ["Keter", "Chochmah", "Binah", "Malchut"], "sefirot_expressa": ["Netzach", "Hod"],
     "entidades": [],
     "observacoes": "O trecho apresenta uma tabela de correspondências entre a hierarquia de necessidades de Maslow, o Tabernáculo e as Sefirot, destacando Prazer e Fé como níveis acima da autorrealização."},
    # de "Kabbalah Approach.odt"
    {"pasta": "Divididos/kabbalah_approach", "chave": "01_conexão_única_à_torá_e_o_paradigma_profético_de_moisés.txt", "autoria": "fonte_externa",
     "temas": ["Educacao", "Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Mashiach", "Shechinah"],
     "observacoes": "O trecho explora a ideia de que cada judeu possui uma conexão única e pessoal à Torá, exemplificada pelo paradigma profético de Moisés como canal transparente da Divina Presença, projetando essa experiência para uma era messiânica de profecia universal."},
    {"pasta": "Divididos/kabbalah_approach", "chave": "02_a_fala_como_veste_da_alma_do_pensamento_consciente_ao_subcon.txt", "autoria": "fonte_externa",
     "temas": ["Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho explora a fala como veste intermediária entre pensamento e ação, capaz de revelar conteúdos subconscientes da alma quando a censura da mente consciente é relaxada, com aplicação ao papel terapêutico."},
    # de "Klalei.txt"
    {"pasta": "Divididos/klalei", "chave": "01_introdução_e_índice_geral_da_obra.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Trecho introdutório e sumário de uma obra sobre princípios de Educação e Orientação chassídica, com nota de rodapé remetendo o acróstico Chochmah-Binah-Da'at ao capítulo sobre Sefirot."},
    {"pasta": "Divididos/klalei", "chave": "02_a_ciência_dos_talentos_aplicada_à_educação.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Nefesh_dimensao"],
     "observacoes": "O trecho apresenta a educação como ciência baseada em talentos dados por D-us, forças da alma que se investem e se dividem entre efeitos materiais e espirituais."},
    {"pasta": "Divididos/klalei", "chave": "03_diferença_entre_ensino_e_educaçãoorientação.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho contrasta o trabalho intelectual do ensino com a tarefa mais ampla e arriscada de Educação e Orientação, que lida com a natureza bruta e material da pessoa desde a infância."},
    {"pasta": "Divididos/klalei", "chave": "04_o_amor_próprio_como_inimigo_da_autocrítica.txt", "autoria": "traducao_propria",
     "temas": ["Humildade", "Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho alerta que o 'amor próprio' selvagem é o maior inimigo da autocrítica moral, cegando o intelecto e distorcendo a autopercepção, e defende a necessidade de vigilância racional constante sobre esse instinto para cumprir o propósito espiritual da vida."},
    {"pasta": "Divididos/klalei", "chave": "05_1_condição_autocrítica_do_educador_-_virtudes_e_defeitos.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": ["Gevurah"],
     "entidades": [],
     "observacoes": "O trecho trata da autocrítica como primeira condição do educador, mostrando que cada pessoa possui virtudes e defeitos (de nascimento e de costume) que podem e devem ser trabalhados, sendo o esforço de transformar o defeito em virtude a fonte de maior satisfação e crescimento moral."},
    {"pasta": "Divididos/klalei", "chave": "06_2_condição_adequação_do_educador_-_modos_e_linguagem.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho descreve a segunda condição do educador — autocrítica constante e cuidado com o tom, as palavras e a paciência ao corrigir e instruir, evitando desprezo ou agitação para não prejudicar o aluno."},
    {"pasta": "Divididos/klalei", "chave": "07_3_condição_percepção_da_essência_e_situação_do_discípulo.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": ["Chochmah", "Binah", "Daat"],
     "entidades": ["Nefesh_dimensao"],
     "observacoes": "O trecho detalha a terceira condição da educação chassídica: a necessidade de o Educador avaliar tanto a essência/caráter quanto a situação do aluno, distinguindo essa tarefa da do professor comum, e conclui que todas as almas são intrinsecamente iguais, diferindo apenas na revelação de seus potenciais."},
    {"pasta": "Divididos/klalei", "chave": "08_a_essência_individual_do_discípulo_-_exemplos_e_limites.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho discute como o Educador deve avaliar e respeitar a essência individual e única de cada discípulo, com exemplos práticos de erros relativos ao caráter de cada pessoa e os limites de tentar elevar alguém acima de sua natureza."},
    {"pasta": "Divididos/klalei", "chave": "09_classificação_das_pessoas_em_quatro_categorias.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho apresenta uma classificação prática das pessoas em quatro categorias (ocupação, situação financeira, costume, lugar) para orientar métodos de Educação e Orientação adequados a cada perfil."},
    {"pasta": "Divididos/klalei", "chave": "10_adequação_da_educação_à_idade.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho discute como a Educação e Orientação deve ser graduada conforme a idade e capacidade do aluno, usando analogias (crescimento humano, alimento físico, vestimenta) para ilustrar a necessidade de progressão adequada de ensinamentos morais e religiosos."},
    {"pasta": "Divididos/klalei", "chave": "11_categoria_a_dedicados_ao_estudo_vs_negociantes.txt", "autoria": "traducao_propria",
     "temas": ["Educacao", "Financas"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho distingue as ocupações de 'dedicados ao estudo' e 'negociantes', mostrando que essa divisão não é anímica mas prática, e discute as diferentes exigências de educação, comportamento e permissividade moral entre esses dois grupos."},
    {"pasta": "Divididos/klalei", "chave": "12_categoria_b_ricos_e_pobres_-_as_dez_naturezas.txt", "autoria": "traducao_propria",
     "temas": ["Financas", "Educacao", "Autoestima", "Humildade"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho classifica as pessoas segundo riqueza ou pobreza, descrevendo as cinco naturezas de cada polo (autoconfiança/orgulho vs. humildade/abatimento) e defende que a Educação e Orientação deve ser adaptada a cada perfil, curando os excessos e fortalecendo as virtudes de cada natureza."},
    {"pasta": "Divididos/klalei", "chave": "13_categoria_c_os_hábitos.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho classifica os hábitos como uma força quase-natural que age por decreto e domínio sobre corpo e alma, e defende que a Educação deve fortalecer os bons hábitos e erradicar os maus, orientando o indivíduo aos caminhos da Torah."},
    {"pasta": "Divididos/klalei", "chave": "14_categoria_d_local_de_moradia_e_a_natureza_dupla_do_homem.txt", "autoria": "traducao_propria",
     "temas": [], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho contrasta a natureza única do homem - composto de elementos superiores (como anjos/Sefirot) e inferiores (como criaturas terrestres), agindo tanto pelo corpo quanto pela alma - com a influência determinante do ambiente e local de moradia (cidade grande ou pequena) sobre todos os aspectos de sua vida."},
    {"pasta": "Divididos/klalei", "chave": "15_4_condição_o_agradável_e_o_repugnante.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho detalha a quarta condição do Educador: discernir com sabedoria o que é agradável ou repugnante para cada educando, adequando seu julgamento e comunicação para fortalecer a confiança e a aceitação de seus ensinamentos."},
    {"pasta": "Divididos/klalei", "chave": "16_5_condição_reflexão_ponderada_e_firmeza_educativa.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": ["Chesed", "Gevurah"],
     "entidades": [],
     "observacoes": "O trecho detalha a 5ª condição da Educação e Orientação: a necessidade de avaliação cuidadosa e ponderada do educando (analogia do artesão) e a combinação de firmeza inabalável com amor e bons modos para formar uma base educacional sólida e duradoura."},
    {"pasta": "Divididos/klalei", "chave": "17_6_condição_as_forças_da_alma_-_pnimiim_e_makifim.txt", "autoria": "traducao_propria",
     "temas": ["Fundamentos"], "sefirot_define": [], "sefirot_expressa": ["Chochmah", "Binah", "Daat"],
     "entidades": ["Nefesh_nivel", "Pnimi", "Makif"],
     "observacoes": "O trecho detalha a divisão das forças da alma humana em dois sistemas estruturais - Pnimiim (internas, específicas) e Makifim (circundantes, gerais) - destacando as particularidades do prazer e da vontade dentro do sistema makif."},
    {"pasta": "Divididos/klalei", "chave": "18_atributos_intrínsecos_e_figurativos_-_ordem_de_correção.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": ["Keter"], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho define a natureza intrínseca versus figurativa da vontade (e demais faculdades da alma) e aplica esse princípio pedagogicamente, orientando o Educador a corrigir com discernimento e ordem de prioridade as falhas mais prejudiciais do educando."},
    {"pasta": "Divididos/klalei", "chave": "19_7_condição_elogio_recompensa_e_punição.txt", "autoria": "traducao_propria",
     "temas": ["Educacao"], "sefirot_define": [], "sefirot_expressa": ["Chesed", "Gevurah"],
     "entidades": [],
     "observacoes": "O trecho discute o papel do Educador/Orientador em dosar elogios, recompensas, críticas e punições como ferramentas para moldar o caráter do educado, evocando implicitamente a dinâmica de Chesed (recompensa) e Gevurah (punição)."},
    # de "Mashiach and Jewish Leadership:  The Power of Rectified Speech.odt"
    {"pasta": "Divididos/mashiach_and_jewish_leadership_the_power_of_rectified_speech", "chave": "01_fala_e_realeza_fundamentos_bíblicos_e_cabalísticos_de_malchu.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca", "Fundamentos"], "sefirot_define": ["Malchut"], "sefirot_expressa": [],
     "entidades": ["Mashiach"],
     "observacoes": "O trecho estabelece as bases bíblicas e cabalísticas de 'malchut peh', ligando o poder da fala à liderança e à realeza (Malchut) como reflexo do ato criador divino."},
    {"pasta": "Divididos/mashiach_and_jewish_leadership_the_power_of_rectified_speech", "chave": "02_o_poder_transformador_e_perigoso_da_fala_da_antiguidade_à_er.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca"], "sefirot_define": ["Malchut"], "sefirot_expressa": ["Malchut"],
     "entidades": [],
     "observacoes": "O trecho explora a faculdade divina da fala (equivalente à ação, associada a Malchut) e sua contrapartida humana, mostrando como a palavra — ampliada pela mídia moderna — pode construir ou destruir liderança e sociedade, citando o exemplo de Hitler como advertência."},
    {"pasta": "Divididos/mashiach_and_jewish_leadership_the_power_of_rectified_speech", "chave": "03_sefer_yetzirah_o_mês_de_nissan_e_a_tribo_de_judá_como_fonte.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Mashiach"],
     "observacoes": "O trecho explora, via Sefer Yetzirah, como a letra hei e o mês de Nissan associam fala e liderança à tribo de Judá, fonte da linhagem davídica e do Mashiach."},
    {"pasta": "Divididos/mashiach_and_jewish_leadership_the_power_of_rectified_speech", "chave": "04_o_significado_de_hod_reconhecimento_louvor_e_confissão_em_ju.txt", "autoria": "fonte_externa",
     "temas": ["Humildade"], "sefirot_define": ["Hod"], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho define a sefirá de Hod através da raiz da palavra 'Judá', explorando seus significados de reconhecimento, louvor e confissão, ilustrados pelos exemplos de Judá com Tamar e do Rei David diante do profeta Natan."},
    {"pasta": "Divididos/mashiach_and_jewish_leadership_the_power_of_rectified_speech", "chave": "05_os_três_estágios_do_serviço_divino_segundo_o_baal_shem_tov_s.txt", "autoria": "fonte_externa",
     "temas": ["Humildade"], "sefirot_define": ["Hod"], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho define os múltiplos significados de Hod (reconhecimento, louvor, agradecimento, glória) na fala, mapeando-os aos três estágios do serviço divino do Baal Shem Tov: submissão (hachna'ah), separação (havdalah) e adoçamento (hamtakah)."},
    {"pasta": "Divididos/mashiach_and_jewish_leadership_the_power_of_rectified_speech", "chave": "06_adoçar_a_realidade_pela_fala_e_a_redenção_messiânica_através.txt", "autoria": "fonte_externa",
     "temas": ["Lideranca", "Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Mashiach"],
     "observacoes": "O trecho explora o poder redentor da fala — tanto para adoçar a ansiedade individual quanto como veículo pelo qual o Mashiach conquistará e purificará o mundo através da linguagem pura."},
    # de "Shalom Bayit: Marital Harmony.odt"
    {"pasta": "Divididos/shalom_bayit_marital_harmony", "chave": "01_shalom_bayit_conceito_expectativas_e_o_choque_da_realidade_c.txt", "autoria": "fonte_externa",
     "temas": ["Casamento"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho aborda o ideal de Shalom Bayit, contrastando expectativas românticas idealizadas com a realidade do esforço contínuo necessário para harmonizar almas gêmeas predestinadas segundo Talmud e Cabala."},
    {"pasta": "Divididos/shalom_bayit_marital_harmony", "chave": "02_fundamentos_da_torá_para_a_prioridade_da_paz_conjugal_e_a_un.txt", "autoria": "fonte_externa",
     "temas": ["Casamento"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho argumenta, com base em fontes talmúdicas e bíblicas, que a Torá dá prioridade máxima à paz conjugal, unindo marido e mulher como 'duas metades de um todo' cujo conflito é visto como tragédia compartilhada e nacional."},
    {"pasta": "Divididos/shalom_bayit_marital_harmony", "chave": "03_empatia_aceitação_de_diferenças_e_foco_no_essencial_do_casam.txt", "autoria": "fonte_externa",
     "temas": ["Casamento", "Autoestima"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho ensina a tratar as falhas do cônjuge com a mesma empatia e foco construtivo que temos por nós mesmos, aceitando diferenças e priorizando o que é essencial no casamento."},
    {"pasta": "Divididos/shalom_bayit_marital_harmony", "chave": "04_intervenção_externa_terceiros_mediação_e_os_limites_do_acons.txt", "autoria": "fonte_externa",
     "temas": ["Casamento"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho discute quando e como terceiros (rabinos, terapeutas, amigos, familiares) devem intervir em conflitos matrimoniais, usando Aharon como modelo de mediador de paz e alertando contra conselhos bem-intencionados que reforçam a discórdia, exceto em casos de abuso."},
    {"pasta": "Divididos/shalom_bayit_marital_harmony", "chave": "05_o_casamento_como_parceria_trina_com_dus_torá_mitzvot_e_a_met.txt", "autoria": "fonte_externa",
     "temas": ["Casamento"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho apresenta o casamento como uma parceria trina entre homem, mulher e D'us, ilustrada pela metáfora das letras yud-hei (nome Divino) que, unidas às letras comuns de ish/isha, formam aish (fogo), sendo a presença Divina o que sustenta essa chama e traz harmonia ao lar através de Torá e mitzvot."},
    {"pasta": "Divididos/shalom_bayit_marital_harmony", "chave": "06_pureza_familiar_taharat_hamishpachah_como_fonte_de_renovação.txt", "autoria": "fonte_externa",
     "temas": ["Casamento"], "sefirot_define": [], "sefirot_expressa": ["Yesod"],
     "entidades": [],
     "observacoes": "O trecho apresenta as leis de Pureza Familiar (Taharat HaMishpachah) como prática prática e espiritual que renova a intimidade e fortalece a harmonia conjugal."},
    {"pasta": "Divididos/shalom_bayit_marital_harmony", "chave": "07_mezuzot_tzedacá_e_reconciliação_com_relacionamentos_passados.txt", "autoria": "fonte_externa",
     "temas": ["Casamento"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho recomenda práticas concretas — verificação de mezuzot e tefillin, prática de tzedacá e reconciliação com relacionamentos passados — como remédios espirituais para restaurar a harmonia conjugal (shalom bayit)."},
    # de "The Purpose of the Soul’s Descent to This World.odt"
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "01_introdução_editorial_propósito_da_descida_da_alma.txt", "autoria": "fonte_externa",
     "temas": ["Proposito", "Humildade"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Introdução editorial que enquadra o propósito da descida da alma como o cumprimento da 'dirá betachtonim' através do bittul e do serviço humano nas atividades mundanas, além de explicar a diferença entre maamar e sichah."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "02_o_voto_de_yaakov_a_pergunta_dos_comentaristas.txt", "autoria": "fonte_externa",
     "temas": [], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho resolve a aparente contradição no voto condicional de Yaakov, argumentando que sua verdadeira intenção era cumprir o voto e não obter recompensa por bom comportamento."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "03_rashi_e_ramban_duas_leituras_do_voto_e_das_condições.txt", "autoria": "fonte_externa",
     "temas": [], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Análise exegética minuciosa das diferentes divisões de versículos por Rashi e Ramban sobre o voto e as condições de Yaakov em Beit-El."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "04_a_descida_de_yaakov_a_charã_como_descida_para_ascensão.txt", "autoria": "fonte_externa",
     "temas": ["Financas", "Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Tzadik"],
     "observacoes": "O trecho explica a descida de Yaakov a Charan como 'descida para ascensão', detalhando três dimensões dessa elevação espiritual (resistência ao ambiente, procriação/cumprimento do mandamento divino, e refinamento das centelhas de santidade através do trabalho com as ovelhas de Lavan), usado como metáfora dentro de uma série sobre investimento/finanças."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "05_paralelo_alma-mundo_a_descida_da_alma_ao_plano_material.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Tzadik"],
     "observacoes": "O trecho usa a jornada de Yaakov como paralelo para a descida da alma ao mundo material, mostrando como essa descida (de nível tzadik a baal teshuvah) e o serviço com entidades físicas cumprem o propósito de tornar o mundo uma morada para D'us, valorizando a santificação do material sobre o estudo da Torá isoladamente."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "06_tzadik_e_baal_teshuvá_mitzvot_versus_assuntos_pessoais.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Tzadik"],
     "observacoes": "O trecho compara os dois modos de serviço divino - cumprir mitzvot (modo de tzadik, expressão da vontade interior) versus lidar com assuntos pessoais/materiais 'pelo bem do Céu' (modo de baal teshuvá) - argumentando pela superioridade deste último por refletir o refinamento da matéria e o objetivo da descida da alma ao mundo físico."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "07_a_profundidade_do_vínculo_revelado_pela_teshuvá.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho compara a teshuvá do arrependimento e a do serviço via Torá/mitsvot com a teshuvá mais profunda alcançada ao dedicar os próprios assuntos cotidianos 'pelo bem dos Céus', revelando um vínculo alma-D'us ainda mais íntimo."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "08_além_da_natureza_da_alma_tornar_o_mundo_uma_morada.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Nefesh_dimensao"],
     "observacoes": "O trecho contrasta o vínculo natural da alma com D'us (limitado por sua essência) com o vínculo superior alcançado ao transformar o mundo material em morada Divina através da unidade ilimitada de D'us."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "09_o_propósito_da_descida_da_alma_não_é_para_si_mesma.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Nefesh_dimensao"],
     "observacoes": "O trecho argumenta que a descida e ascensão da alma não são fins em si mesmas, mas servem ao propósito Divino de criar uma morada nos mundos inferiores, sendo a elevação da alma um benefício secundário."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "10_bittul_de_ein_od_e_o_servo_simples.txt", "autoria": "fonte_externa",
     "temas": ["Humildade", "Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho explica que a morada Divina nos mundos inferiores exige do homem um serviço de bittul total, equiparado ao bittul de ein od, expresso na figura chassídica do 'servo simples' cuja submissão não depende de apreciar as qualidades do senhor, mas emana do próprio senhor."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "11_interpretação_final_do_voto_de_yaakov_à_luz_da_alma.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Neshamah_nivel"],
     "observacoes": "O trecho interpreta o voto de Yaakov como alegoria da dupla missão da alma na descida ao mundo material: servir a D'us via Torá/mitzvot e sanctificar os assuntos mundanos, culminando na ascensão da alma e na criação de uma morada Divina nos mundos inferiores."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "12_nota_de_navegação_entre_artigos.txt", "autoria": "fonte_externa",
     "temas": [], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Trecho puramente estrutural/de navegação (links 'Previous/Next' entre artigos sobre Vayeitzei), sem conteúdo filosófico a classificar."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "13_introdução_editorial_versão_bilíngue_inglês-iídiche.txt", "autoria": "fonte_externa",
     "temas": ["Proposito", "Humildade"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Introdução editorial que contextualiza a sichah como derivada de um maamar, articulando os temas de bittul e da morada Divina no mundo material através do serviço humano."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "14_o_voto_de_yaakov_pergunta_dos_comentaristas_bilíngue.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho resolve a questão dos comentaristas sobre o voto de Yaakov, mostrando que sua intenção não era condicionar boas ações a uma recompensa, mas sim usar a condição como o único meio de cumprir seu voto por si mesmo."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "15_rashi_e_ramban_sobre_o_voto_bilíngue.txt", "autoria": "fonte_externa",
     "temas": [], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Análise textual/exegética da disputa entre Rashi e Ramban sobre como dividir os versículos do voto e da condição de Yaakov, sem relação direta com Sefirot ou temas práticos da lista."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "16_duas_naturezas_nas_condições_e_no_voto_bilíngue.txt", "autoria": "fonte_externa",
     "temas": [], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Análise exegética da divisão do voto e das condições de Yaakov em dois versículos, contrastando ações atribuídas a D-us e a iniciativa própria de Yaakov ao retornar."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "17_a_descida_de_yaakov_a_charã_bilíngue.txt", "autoria": "fonte_externa",
     "temas": ["Financas"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Tzadik"],
     "observacoes": "O trecho explica a descida de Yaakov a Charã como uma 'descida para propósito de ascensão', detalhando três dimensões desse crescimento: resistir ao ambiente negativo (paralelo ao baal teshuvah vs tzadik), cumprir o mandamento de procriação, e refinar as centelhas de santidade através do trabalho com o gado de Lavan."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "18_paralelo_alma-mundo_descida_da_alma_bilíngue.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Neshamah_nivel", "Tzadik"],
     "observacoes": "O trecho usa a jornada de Yaakov de Beersheba a Charan como paralelo à descida da alma ao mundo material, detalhando três aspectos dessa 'descida para ascensão' que culminam no objetivo de transformar o mundo em morada para D-us (dirá betachtonim), com destaque para a vantagem do serviço nas 'coisas permitidas' sobre o estudo puro da Torá."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "19_tzadik_e_baal_teshuvá_mitzvot_vs_assuntos_pessoais_bilíngue.txt", "autoria": "fonte_externa",
     "temas": [], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Tzadik"],
     "observacoes": "O trecho contrasta o cumprimento de mitzvot, que expressa a vontade interior do judeu (nível de tzadik), com o serviço divino através de assuntos pessoais/materiais, que segue o modo de avodá do baal teshuvah por exigir superação da natureza do corpo e da alma animal."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "20_a_profundidade_do_vínculo_pela_teshuvá_bilíngue.txt", "autoria": "fonte_externa",
     "temas": [], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Neshamah_nivel"],
     "observacoes": "O trecho compara níveis de teshuvá, mostrando que o serviço divino nos assuntos cotidianos e mundanos revela um vínculo da alma com D'us ainda mais profundo do que o alcançado pela vitória sobre o yetzer hara na Torá e mitsvot."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "21_além_da_natureza_da_alma_rumo_à_morada_divina_bilíngue.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Neshamah_nivel"],
     "observacoes": "O trecho compara o vínculo da alma com D-us baseado em sua natureza limitada com o vínculo superior alcançado ao transformar o mundo material em morada divina, possibilitado pela unidade infinita de D-us."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "22_o_propósito_não-egocêntrico_da_descida_da_alma_bilíngue.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Neshamah_nivel"],
     "observacoes": "O trecho explica que o propósito final da descida da alma não é sua própria elevação, mas cumprir a intenção Divina de criar uma morada nos mundos inferiores, sendo a elevação da alma um benefício secundário."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "23_bittul_de_ein_od_resolução_final_bilíngue.txt", "autoria": "fonte_externa",
     "temas": ["Proposito", "Humildade"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Neshamah_nivel"],
     "observacoes": "Resolução final sobre como o bittul de 'ein od' se manifesta no mundo material através da avodá do homem como 'eved pashut', realizando o propósito de dirá betachtonim e explicando a verdadeira ascensão da alma através da descida."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "24_interpretação_completa_do_voto_de_yaakov_bilíngue.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho interpreta o voto de Yaakov como estrutura dupla que espelha o propósito da descida da alma: serviço via Torá/mitzvot e via assuntos mundanos (teshuvá), culminando na ascensão da alma e na criação de uma morada para D-us nos mundos inferiores."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "25_rashi_e_a_ascensão_como_meio_não_fim_bilíngue.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho compara as interpretações de Rashi e Ramban sobre o voto de Yaakov, mostrando que mesmo para Rashi a ascensão da alma é meio preparatório e não fim, sendo o propósito último a criação de uma morada para D'us no plano material."},
    {"pasta": "Divididos/the_purpose_of_the_souls_descent_to_this_world", "chave": "26_referência_da_fonte_original.txt", "autoria": "fonte_externa",
     "temas": [], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Trecho consiste apenas no link de referência da fonte original em chabad.org, sem conteúdo textual a classificar."},
    # de "The Secret of Enclothement.odt"
    {"pasta": "Divididos/the_secret_of_enclothement", "chave": "01_o_óleo_da_unção_e_a_missão_do_mashiach.txt", "autoria": "fonte_externa",
     "temas": ["Proposito"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Mashiach"],
     "observacoes": "O trecho explica o óleo de oliva usado na unção e no Menorá como símbolo de que toda matéria é luz divina condensada, e apresenta a missão do Mashiach como ensinar essa unidade entre o físico e o espiritual, expressão da paixão divina de habitar os mundos inferiores."},
    {"pasta": "Divididos/the_secret_of_enclothement", "chave": "02_o_conceito_cabalístico_de_enclothement_hitlabshut.txt", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": ["Nefesh_dimensao"],
     "observacoes": "O trecho explica o conceito cabalístico-chassídico de hitlabshut (enclothement) — a luz infinita de Deus revestida na natureza finita, exemplificada pela alma no corpo e pela matéria que enclothes energia, com as mitzvot servindo para revelar a centelha divina oculta na realidade física."},
    {"pasta": "Divididos/the_secret_of_enclothement", "chave": "03_concealment_and_revelation_das_vestes_sagradas_ao_nome_ocult.txt", "autoria": "fonte_externa",
     "temas": ["Fundamentos"], "sefirot_define": [], "sefirot_expressa": ["Keter"],
     "entidades": ["Tzadik"],
     "observacoes": "O trecho explora o paradoxo de ocultação e revelação — nas vestes, na natureza, na Meguilá de Ester e na ausência do nome de Moshé em Tetzavê — como expressão da providência Divina oculta e do nível espiritual de autossacrifício ligado a Keter."},
    # de "positive self-image.odt"
    {"pasta": "Divididos/positive_self-image", "chave": "01_a_importância_de_uma_autoimagem_positiva.txt", "autoria": "fonte_externa",
     "temas": ["Autoestima", "Saude_Mental"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "O trecho aconselha equilíbrio entre reconhecer falhas e qualidades próprias, alertando que a autodepreciação é tática da inclinação ao mal para impedir ações positivas."},
    {"pasta": "Divididos/positive_self-image", "chave": "02_assunto_administrativo_sobre_publicação_de_maamarim_e_fonte.txt", "autoria": "fonte_externa",
     "temas": ["Financas"], "sefirot_define": [], "sefirot_expressa": [],
     "entidades": [],
     "observacoes": "Carta administrativa pedindo ajuda para viabilizar a publicação de maamarim e sichos, atrasada por questões de custo de impressão."},
]

# Arquivo vazio confirmado (nao entra no corpus, so registrado por completude)
ARQUIVOS_VAZIOS = [
    {"pasta": "Novos/10", "chave": "Personal Finance",
     "observacoes": "ARQUIVO VAZIO - confirmado no XML interno do .odt."},
]
